# Generated by Django 4.0.6 on 2022-08-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0004_alter_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AlterField(
            model_name='class_attendance',
            name='Chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class_attendance',
            name='Maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class_attendance',
            name='Physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class_attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_record', to='attendance_marker.student'),
        ),
    ]
