# Generated by Django 4.0.6 on 2022-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0005_remove_attendance_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_location_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_location_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='UID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
