# Generated by Django 4.0.6 on 2022-08-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0008_attendance_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_code',
        ),
    ]
