# Generated by Django 4.0.6 on 2022-08-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0009_remove_attendance_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_location_x',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_location_y',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
    ]
