# Generated by Django 4.0.6 on 2022-08-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0011_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class_details',
        ),
    ]
