# Generated by Django 4.0.6 on 2022-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0012_rename_class_class_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
