# Generated by Django 4.0.6 on 2022-08-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0013_class_details_altitude_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='altitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='lat_1',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='lat_2',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='long_1',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='long_2',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
    ]
