# Generated by Django 4.0.6 on 2022-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0014_alter_class_details_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_location_x',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_location_y',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=50),
        ),
    ]
