# Generated by Django 4.0.6 on 2022-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0015_alter_student_class_location_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_location_x',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_location_y',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='altitude',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='lat_1',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='lat_2',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='long_1',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='class_details',
            name='long_2',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_location_x',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_location_y',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
