# Generated by Django 4.0.6 on 2022-08-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0016_alter_attendance_class_location_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_location_x',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_location_y',
        ),
    ]
