# Generated by Django 4.0.6 on 2022-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_marker', '0018_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
